### ISSUE TITLE
ya..

### ISSUE THREAD

**Issue by PatrickSantoZZ** [thebobbyb/teraCZ-proxy#1]
you know that all mods are outdated as fck? as an example Memeslash from your modfolder. S_LOGIN / S_SPAWN_NPC 2 / S_DESPAWN_NPC 1
source isnt used/changed to a other name in the new versions so you need to rewrite the mod.

:)

**Comment by terascripter** [comment]
maybe because this is for a private server that runs in lucid patch, dumbass?
